DATA = {
"ABACUS":"Around 4000 years ago, the Chinese invented the Abacus, and it is believed to be the first computer. The history of computers begins with the birth of the abacus. Structure: Abacus is basically a wooden rack that has metal rods with beads mounted on them.Working of abacus: In the abacus, the beads were moved by the abacus operator according to some rules to perform arithmetic calculations. In some countries like China, Russia, and Japan, the abacus is still used by their people.",
"NAPIER'S BONES":"Was a manually operated calculating device and as the name indicates, it was invented by John Napier. In this device, he used 9 different ivory strips (bones) marked with numbers to multiply and divide for calculation. It was also the first machine to use the decimal point system for calculation.",
"PASCALINE":"It is also called an Arithmetic Machine or Adding Machine. A French mathematician-philosopher Blaise Pascal invented this between 1642 and 1644. It was the first mechanical and automatic calculator. It is invented by Pascal to help his father, a tax accountant in his work or calculation. It could perform addition and subtraction in quick time. It was basically a wooden box with a series of gears and wheels. It is worked by rotating wheel like when a wheel is rotated one revolution, it rotates the neighbouring wheel and a series of windows is given on the top of the wheels to read the totals.",
"STEPPED RECKONER OR LEIBNIZ WHEEL":"A German mathematician-philosopher Gottfried Wilhelm Leibniz in 1673 developed this device by Improving Pascal's invention to develop this machine. It was basically a digital mechanical calculator, and it was called the stepped reckoner as it was made of fluted drums instead of gears (used in the previous model of Pascaline)",
"ANALYTICAL ENGINE":"Again in 1830 Charles Babbage developed another calculating machine which was Analytical Engine. Analytical Engine was a mechanical computer that used punch cards as Input. It was capable of performing or solving any mathematical problem and storing information as a permanent memory (storage)",
"TABULATING MACHINE":"Herman Hollerith, an American statistician invented this machine in the year 1890. Tabulating Machine was a mechanical tabulator that was based on punch cards it was capable of tabulating statistics and record or sort data or information. This machine was used by US Census in the year 1890. Hollerith's Tabulating Machine Company was started by Hollerith and this company later became international Business Machine (IBM) in the year 1924)",
"MARK 1":"In the year 1937, major changes began in the history of computers when Howard Aiken planned to develop a machine that could perform large calculations or calculations involving large numbers. In the year 1944, Mark I computer was built as a partnership between IBM-and-Harvard. It was also the first programmable digital computer marking a new era in the computer world.",
"FIRST GENERATION COMPUTERS":"In the period of the year 1940-1956, it was referred to as the period of the first generation of computers. These machines are slow, huge, and expensive. In this generation of computers, vacuum tubes were used as the basic components of CPU and memory. Also, they were mainly dependent on the batch operating systems and punch cards) Magnetic tape and paper tape were used as output and input devices. For example ENIAC, UNIVAC-1, EDVAC, etc.",
"SECOND GENERATION COMPUTERS":"In the period of the year, 1957-1963 was referred to as the period of the second generation of computers, it was the time of the transistor computers. In the second generation of computers, transistors (which were cheap in cost) are used. Transistors are also compact and consume less power. Transistor computers are faster than the first-generation computers. For primary memory, magnetic cores were used. and for secondary memory magnetic disc and tapes for storage purposes in second generation computers, COBOL and FORTRAN are used Assembly language and programming languages and Batch processing and multiprogramming operating systems wore used in these computers. For example 1BM 1620, IBM 7094, CDC 1604, CDC 3600, etc.",
"THIRD GENERTION COMPUTERS":"Spanned from 1964 to 1970. In the third generation of computers, integrated circuits (ICs) were used (instead of transistors in the second generation). A single IC consists of many transistors which increased the power of a computer and also reduced the cost. The third generation computers are more reliable, efficient, and smaller in size. It used remote processing, time-sharing, and multiprogramming as operating systems. FORTRON-II TO IV, COBOL, and PASCAL PL/1 were used which are high-level programming languages. For example IBM-360 series, Honeywell-6000 series, IBM-370/168, etc.",
"FOURTH GENERATION COMPUTERS":"The period of 1971-1990 was mainly the time of fourth generation computers. It used VISI(Very Large Scale Integrated) circuits. VLSI is a chip containing millions of transistors and other circuit elements and because of these chips, the computers of this generation are more compact, powerful, fast, and affordable and low in cost). Real-time, time-sharing and distributed operating system are used by these computers. C and C++ is used as the programming languages in this generation of computers. For example STAR 1000, PDP 11, CRAY-1, CRAY-X-MP, etc.",
"FIFTH GENERATION COMPUTERS":"From 1980-to till date these computers are used. The ULSI (Ultra Large Scale Integration) technology is used in fifth-generation computers instead of the VLSI technology of fourth-generation computers. Microprocessor chips with ten million electronic components are used in these computers Parallel processing hardware and AI (Artificial Intelligence) software are also used in fifth-generation computers. The programming languages like C, C++, Java, Net, etc. are used. For example Desktop, Laptop, NoteBook, UltraBook, etc.",
"COMPUTER":"s an electronic device that can receive, store, process, and output data. It is a machine that can perform a variety of tasks and operations, ranging from simple calculations to complex simulations and artificial intelligence. Computers consist of hardware components such as the central processing unit (CPU), memory, storage devices, input/output devices, and peripherals, as well as software components such as the operating system and applications. Today, computers are widely used in various industries such as education, finance, healthcare, and entertainment, and they have revolutionized the way we live, work, and communicate. They have also given rise to a new era of technology such as the internet, cloud computing, and mobile devices, which have further transformed our daily lives.",
"DIGITAL COMPUTERS":"These are the modern computers which are capable of processing information in discrete form. In digital technology data which can be in the form of letters, symbols or numbers is represented in binary form i.e. Os and 1s. The digital computers are used in industrial, business and scientific applications. They are quite suitable for large volume data processing.",
"ANALOG COMPUTERS":"These computers are used to process data generated by ongoing physical processes. A thermometer is an example of an analog computer since it measures the change in mercury level continuously. Analog computers are well suited to simulating systems. A simulator helps to conduct experiments repeatedly in real time environment. Some of the common examples are simulations in aircrafts, nuclear power plants, hydraulic and electronic networks.",
"HYBRID COMPUTERS":"These use both analog and digital technology. It has the speed of analog computer and the accuracy of a digital computer. It may accept digital or analog signals but an extensive conversion of data from digital to analog and analog to digital has to be done. Hybrid Computers are used as a cost effective means for complex simulations.",
"SUPERCOMPUTERS":"These are the most powerful and expensive computers that are used for complex scientific calculations, simulations, and research. They are used in fields such as weather forecasting, cryptography, and nuclear research.",
"MAINFRAME COMPUTERS":"These are large and powerful computers that are used by large organizations such as banks, airlines, and government agencies to process massive amounts of data and handle multiple users simultaneously.",
"MINI COMPUTERS":"These are smaller and less powerful than mainframe computers, but they are still capable of handling multiple users and processing large amounts of data. They are commonly used by small to medium-sized businesses for accounting, inventory management, and other data-intensive tasks.",
"WORKSTATIONS":"These are high performance computers that are used by professionals such as architects, engineers, and designers to run complex software applications for tasks such as 3D modeling, animation, and scientific visualization.",
"EMBEDDED SYSTEM":"These are specialized computers that are built into other devices such as cars, appliances, and medical equipment to control their operations and perform specific functions.",
"MOBILE DEVICES":"These are small and portable computers that are designed for on-the-go use, such as smartphones, tablets, and laptops.",
"MICRO COMPUTERS":"These are also known as Personal Computers. These type of digital computer uses a microprocessor (a CPU on a single chip) and include both desktops and laptops. These computers can work on small volume of data, are very versatile and can handle variety of applications. These computers are being used as work stations, CAD, multimedia and advertising applications. Example: portable computers such as PDAs (Personal Digital Assistants) and tablets.",
"PERIPHERAL DEVICES":"These devices are used in performing the specific functions and are connected to the computer externally. These peripheral devices enable the computer to operatre according to the user requirements by feeding data in and out of the computer.",
"RANDOM ACCESS MEMORY OR RAM":"Is an electronic device that i much faster than a hard disk.",
"HARD DISK DRIVE OR HARD DISK":"Is an electromechanical device that has speed slower than Electronic device.",
"VOLATILE":"The contents are lost when the computer is turned off.",
"NON-VOLATILE":"The contents are preserved even when the computer is turned off.",
"SYSTEM SOFTWARE":" These are those software, without which our PC, laptop won't run, l.e it is must for a device to be operating. For Example: Linux, Unix, Windows, etc.",
"APPLICATION SOFTWARE":"These are those software, without which our PC, laptop can run, i.e these software are not necessary for a device to be operating. For Example: Facebook, What's App,Games.",
"HACKER":"They will just warn you something about malicious activity going around in your computer.It will not steal your information.",
"CRACKER":"They will try to steal your Information without informing you."
}
a = input("say: ")
print(DATA[a])



